# Target local machine (CloudShell, local terminal, or Jenkins Runner)
[local]
localhost ansible_connection=local

# If targeting newly created EC2 worker nodes/bastion servers:
[eks_nodes]
# Replace with your EC2 Elastic IP or private IP AFTER Terraform finishes provisioning
# node1.example.com or IP address
